package cx.cad.pgpwords

object PgpWordList extends WordListSource {

  def tuplesToPairSeq(pairSet: Seq[(String, String)]): Map[Byte, Pair] = {
    pairSet.zipWithIndex.map {
      case (pair, index) =>
        pair match {
          case (even, odd) => index.toByte -> Pair(even, odd)
        }
    }.toMap
  }

  def apply: WordList = WordList(pairs, reversePairs)

  val tuples = IndexedSeq(
    ("aardvark", "adroitness"), // 00
    ("absurd", "adviser"), // 01
    ("accrue", "aftermath"), // 02
    ("acme", "aggregate"), // 03
    ("adrift", "alkali"), // 04
    ("adult", "almighty"), // 05
    ("afflict", "amulet"), // 06
    ("ahead", "amusement"), // 07
    ("aimless", "antenna"), // 08
    ("Algol", "applicant"), // 09
    ("allow", "Apollo"), // 0A
    ("alone", "armistice"), // 0B
    ("ammo", "article"), // 0C
    ("ancient", "asteroid"), // 0D
    ("apple", "Atlantic"), // 0E
    ("artist", "atmosphere"), // 0F
    ("assume", "autopsy"), // 10
    ("Athens", "Babylon"), // 11
    ("atlas", "backwater"), // 12
    ("Aztec", "barbecue"), // 13
    ("baboon", "belowground"), // 14
    ("backfield", "bifocals"), // 15
    ("backward", "bodyguard"), // 16
    ("banjo", "bookseller"), // 17
    ("beaming", "borderline"), // 18
    ("bedlamp", "bottomless"), // 19
    ("beehive", "Bradbury"), // 1A
    ("beeswax", "bravado"), // 1B
    ("befriend", "Brazilian"), // 1C
    ("Belfast", "breakaway"), // 1D
    ("berserk", "Burlington"), // 1E
    ("billiard", "businessman"), // 1F
    ("bison", "butterfat"), // 20
    ("blackjack", "Camelot"), // 21
    ("blockade", "candidate"), // 22
    ("blowtorch", "cannonball"), // 23
    ("bluebird", "Capricorn"), // 24
    ("bombast", "caravan"), // 25
    ("bookshelf", "caretaker"), // 26
    ("brackish", "celebrate"), // 27
    ("breadline", "cellulose"), // 28
    ("breakup", "certify"), // 29
    ("brickyard", "chambermaid"), // 2A
    ("briefcase", "Cherokee"), // 2B
    ("Burbank", "Chicago"), // 2C
    ("button", "clergyman"), // 2D
    ("buzzard", "coherence"), // 2E
    ("cement", "combustion"), // 2F
    ("chairlift", "commando"), // 30
    ("chatter", "company"), // 31
    ("checkup", "component"), // 32
    ("chisel", "concurrent"), // 33
    ("choking", "confidence"), // 34
    ("chopper", "conformist"), // 35
    ("Christmas", "congregate"), // 36
    ("clamshell", "consensus"), // 37
    ("classic", "consulting"), // 38
    ("classroom", "corporate"), // 39
    ("cleanup", "corrosion"), // 3A
    ("clockwork", "councilman"), // 3B
    ("cobra", "crossover"), // 3C
    ("commence", "crucifix"), // 3D
    ("concert", "cumbersome"), // 3E
    ("cowbell", "customer"), // 3F
    ("crackdown", "Dakota"), // 40
    ("cranky", "decadence"), // 41
    ("crowfoot", "December"), // 42
    ("crucial", "decimal"), // 43
    ("crumpled", "designing"), // 44
    ("crusade", "detector"), // 45
    ("cubic", "detergent"), // 46
    ("dashboard", "determine"), // 47
    ("deadbolt", "dictator"), // 48
    ("deckhand", "dinosaur"), // 49
    ("dogsled", "direction"), // 4A
    ("dragnet", "disable"), // 4B
    ("drainage", "disbelief"), // 4C
    ("dreadful", "disruptive"), // 4D
    ("drifter", "distortion"), // 4E
    ("dropper", "document"), // 4F
    ("drumbeat", "embezzle"), // 50
    ("drunken", "enchanting"), // 51
    ("Dupont", "enrollment"), // 52
    ("dwelling", "enterprise"), // 53
    ("eating", "equation"), // 54
    ("edict", "equipment"), // 55
    ("egghead", "escapade"), // 56
    ("eightball", "Eskimo"), // 57
    ("endorse", "everyday"), // 58
    ("endow", "examine"), // 59
    ("enlist", "existence"), // 5A
    ("erase", "exodus"), // 5B
    ("escape", "fascinate"), // 5C
    ("exceed", "filament"), // 5D
    ("eyeglass", "finicky"), // 5E
    ("eyetooth", "forever"), // 5F
    ("facial", "fortitude"), // 60
    ("fallout", "frequency"), // 61
    ("flagpole", "gadgetry"), // 62
    ("flatfoot", "Galveston"), // 63
    ("flytrap", "getaway"), // 64
    ("fracture", "glossary"), // 65
    ("framework", "gossamer"), // 66
    ("freedom", "graduate"), // 67
    ("frighten", "gravity"), // 68
    ("gazelle", "guitarist"), // 69
    ("Geiger", "hamburger"), // 6A
    ("glitter", "Hamilton"), // 6B
    ("glucose", "handiwork"), // 6C
    ("goggles", "hazardous"), // 6D
    ("goldfish", "headwaters"), // 6E
    ("gremlin", "hemisphere"), // 6F
    ("guidance", "hesitate"), // 70
    ("hamlet", "hideaway"), // 71
    ("highchair", "holiness"), // 72
    ("hockey", "hurricane"), // 73
    ("indoors", "hydraulic"), // 74
    ("indulge", "impartial"), // 75
    ("inverse", "impetus"), // 76
    ("involve", "inception"), // 77
    ("island", "indigo"), // 78
    ("jawbone", "inertia"), // 79
    ("keyboard", "infancy"), // 7A
    ("kickoff", "inferno"), // 7B
    ("kiwi", "informant"), // 7C
    ("klaxon", "insincere"), // 7D
    ("locale", "insurgent"), // 7E
    ("lockup", "integrate"), // 7F
    ("merit", "intention"), // 80
    ("minnow", "inventive"), // 81
    ("miser", "Istanbul"), // 82
    ("Mohawk", "Jamaica"), // 83
    ("mural", "Jupiter"), // 84
    ("music", "leprosy"), // 85
    ("necklace", "letterhead"), // 86
    ("Neptune", "liberty"), // 87
    ("newborn", "maritime"), // 88
    ("nightbird", "matchmaker"), // 89
    ("Oakland", "maverick"), // 8A
    ("obtuse", "Medusa"), // 8B
    ("offload", "megaton"), // 8C
    ("optic", "microscope"), // 8D
    ("orca", "microwave"), // 8E
    ("payday", "midsummer"), // 8F
    ("peachy", "millionaire"), // 90
    ("pheasant", "miracle"), // 91
    ("physique", "misnomer"), // 92
    ("playhouse", "molasses"), // 93
    ("Pluto", "molecule"), // 94
    ("preclude", "Montana"), // 95
    ("prefer", "monument"), // 96
    ("preshrunk", "mosquito"), // 97
    ("printer", "narrative"), // 98
    ("prowler", "nebula"), // 99
    ("pupil", "newsletter"), // 9A
    ("puppy", "Norwegian"), // 9B
    ("python", "October"), // 9C
    ("quadrant", "Ohio"), // 9D
    ("quiver", "onlooker"), // 9E
    ("quota", "opulent"), // 9F
    ("ragtime", "Orlando"), // A0
    ("ratchet", "outfielder"), // A1
    ("rebirth", "Pacific"), // A2
    ("reform", "pandemic"), // A3
    ("regain", "Pandora"), // A4
    ("reindeer", "paperweight"), // A5
    ("rematch", "paragon"), // A6
    ("repay", "paragraph"), // A7
    ("retouch", "paramount"), // A8
    ("revenge", "passenger"), // A9
    ("reward", "pedigree"), // AA
    ("rhythm", "Pegasus"), // AB
    ("ribcage", "penetrate"), // AC
    ("ringbolt", "perceptive"), // AD
    ("robust", "performance"), // AE
    ("rocker", "pharmacy"), // AF
    ("ruffled", "phonetic"), // B0
    ("sailboat", "photograph"), // B1
    ("sawdust", "pioneer"), // B2
    ("scallion", "pocketful"), // B3
    ("scenic", "politeness"), // B4
    ("scorecard", "positive"), // B5
    ("Scotland", "potato"), // B6
    ("seabird", "processor"), // B7
    ("select", "provincial"), // B8
    ("sentence", "proximate"), // B9
    ("shadow", "puberty"), // BA
    ("shamrock", "publisher"), // BB
    ("showgirl", "pyramid"), // BC
    ("skullcap", "quantity"), // BD
    ("skydive", "racketeer"), // BE
    ("slingshot", "rebellion"), // BF
    ("slowdown", "recipe"), // C0
    ("snapline", "recover"), // C1
    ("snapshot", "repellent"), // C2
    ("snowcap", "replica"), // C3
    ("snowslide", "reproduce"), // C4
    ("solo", "resistor"), // C5
    ("southward", "responsive"), // C6
    ("soybean", "retraction"), // C7
    ("spaniel", "retrieval"), // C8
    ("spearhead", "retrospect"), // C9
    ("spellbind", "revenue"), // CA
    ("spheroid", "revival"), // CB
    ("spigot", "revolver"), // CC
    ("spindle", "sandalwood"), // CD
    ("spyglass", "sardonic"), // CE
    ("stagehand", "Saturday"), // CF
    ("stagnate", "savagery"), // D0
    ("stairway", "scavenger"), // D1
    ("standard", "sensation"), // D2
    ("stapler", "sociable"), // D3
    ("steamship", "souvenir"), // D4
    ("sterling", "specialist"), // D5
    ("stockman", "speculate"), // D6
    ("stopwatch", "stethoscope"), // D7
    ("stormy", "stupendous"), // D8
    ("sugar", "supportive"), // D9
    ("surmount", "surrender"), // DA
    ("suspense", "suspicious"), // DB
    ("sweatband", "sympathy"), // DC
    ("swelter", "tambourine"), // DD
    ("tactics", "telephone"), // DE
    ("talon", "therapist"), // DF
    ("tapeworm", "tobacco"), // E0
    ("tempest", "tolerance"), // E1
    ("tiger", "tomorrow"), // E2
    ("tissue", "torpedo"), // E3
    ("tonic", "tradition"), // E4
    ("topmost", "travesty"), // E5
    ("tracker", "trombonist"), // E6
    ("transit", "truncated"), // E7
    ("trauma", "typewriter"), // E8
    ("treadmill", "ultimate"), // E9
    ("Trojan", "undaunted"), // EA
    ("trouble", "underfoot"), // EB
    ("tumor", "unicorn"), // EC
    ("tunnel", "unify"), // ED
    ("tycoon", "universe"), // EE
    ("uncut", "unravel"), // EF
    ("unearth", "upcoming"), // F0
    ("unwind", "vacancy"), // F1
    ("uproot", "vagabond"), // F2
    ("upset", "vertigo"), // F3
    ("upshot", "Virginia"), // F4
    ("vapor", "visitor"), // F5
    ("village", "vocalist"), // F6
    ("virus", "voyager"), // F7
    ("Vulcan", "warranty"), // F8
    ("waffle", "Waterloo"), // F9
    ("wallet", "whimsical"), // FA
    ("watchword", "Wichita"), // FB
    ("wayside", "Wilmington"), // FC
    ("willow", "Wyoming"), // FD
    ("woodlark", "yesteryear"), // FE
    ("Zulu", "Yucatan") // FF
  )

  val pairs: Map[Byte, Pair] = tuplesToPairSeq(tuples)

  val reversePairs: Map[String, Byte] = pairs.flatMap{ case(index, pair) => Map(pair.even -> index, pair.odd -> index) }

}

